/**
 * Dictionary of Singular <-> Plural pairs.
 * Each entry maps a normalized word to its Singular (s) and Plural (p) forms.
 * We include both directions (Key=Singular, Key=Plural) for easy O(1) lookup.
 */
const WORD_FORMS = {
    // --- HEBREW UNITS (Standard) ---
    "כוס": { s: "כוס", p: "כוסות" },
    "כוסות": { s: "כוס", p: "כוסות" },
    "ספל": { s: "ספל", p: "ספלים" },
    "ספלים": { s: "ספל", p: "ספלים" },
    "כף": { s: "כף", p: "כפות" },
    "כפות": { s: "כף", p: "כפות" },
    "כפית": { s: "כפית", p: "כפיות" },
    "כפיות": { s: "כפית", p: "כפיות" },
    "כף גדושה": { s: "כף גדושה", p: "כפות גדושות" },
    "כפות גדושות": { s: "כף גדושה", p: "כפות גדושות" },
    "כף מלאה": { s: "כף מלאה", p: "כפות מלאות" },
    "כפות מלאות": { s: "כף מלאה", p: "כפות מלאות" },
    "כפית גדושה": { s: "כפית גדושה", p: "כפיות גדושות" },
    "כפיות גדושות": { s: "כפית גדושה", p: "כפיות גדושות" },
    "כפית מלאה": { s: "כפית מלאה", p: "כפיות מלאות" },
    "כפיות מלאות": { s: "כפית מלאה", p: "כפיות מלאות" },
    "מיכל": { s: "מיכל", p: "מיכלים" },
    "מיכלים": { s: "מיכל", p: "מיכלים" },
    "גביע": { s: "גביע", p: "גביעי" },
    "גביעים": { s: "גביע", p: "גביעי" },
    "שקית": { s: "שקית", p: "שקיות" },
    "שקיות": { s: "שקית", p: "שקיות" },
    "חבילה": { s: "חבילה", p: "חבילות" },
    "חבילות": { s: "חבילה", p: "חבילות" },
    "חבילת": { s: "חבילת", p: "חבילות" },
    "קופסה": { s: "קופסה", p: "קופסאות" },
    "קופסאות": { s: "קופסה", p: "קופסאות" },
    "קופסה קטנה": { s: "קופסה קטנה", p: "קופסאות קטנות" },
    "קופסאות קטנות": { s: "קופסה קטנה", p: "קופסאות קטנות" },
    "קופסת": { s: "קופסת", p: "קופסאות" },
    "קופסת שימורים": { s: "קופסת שימורים", p: "קופסאות שימורים" },
    "צנצנת": { s: "צנצנת", p: "צנצנות" },
    "צנצנות": { s: "צנצנת", p: "צנצנות" },
    "בקבוק": { s: "בקבוק", p: "בקבוקים" },
    "בקבוקים": { s: "בקבוק", p: "בקבוקים" },
    "פחית": { s: "פחית", p: "פחיות" },
    "פחיות": { s: "פחית", p: "פחיות" },
    "יחידה": { s: "יחידה", p: "יחידות" },
    "יחידות": { s: "יחידה", p: "יחידות" },
    "חופן": { s: "חופן", p: "חופנים" },
    "חופנים": { s: "חופן", p: "חופנים" },
    "קורט": { s: "קורט", p: "קורט" },
    "טיפה": { s: "טיפה", p: "טיפות" },
    "טיפות": { s: "טיפה", p: "טיפות" },
    "ראש": { s: "ראש", p: "ראשים" },
    "ראשים": { s: "ראש", p: "ראשים" },
    "צרור": { s: "צרור", p: "צרורות" },
    "צרורות": { s: "צרור", p: "צרורות" },
    "גבעול": { s: "גבעול", p: "גבעולי" },
    "גבעולים": { s: "גבעול", p: "גבעולי" },
    "עלה": { s: "עלה", p: "עלי" },
    "עלי": { s: "עלה", p: "עלי" },
    "חתיכה": { s: "חתיכה", p: "חתיכות" },
    "חתיכות": { s: "חתיכה", p: "חתיכות" },
    "חתיכת": { s: "חתיכת", p: "חתיכות" },
    "סלסלה": { s: "סלסלה", p: "סלסלות" },
    "סלסלות": { s: "סלסלה", p: "סלסלות" },
    "קוביה": { s: "קוביה", p: "קוביות" },
    "קוביות": { s: "קוביה", p: "קוביות" },
    "פרוסה": { s: "פרוסה", p: "פרוסות" },
    "פרוסות": { s: "פרוסה", p: "פרוסות" },
	"סלסלת": { s: "סלסלת", p: "סלסלות" },
    "סלסלות": { s: "סלסלת", p: "סלסלות" },

    // --- HEBREW MEASUREMENTS (Invariant abbreviations) ---
    "ליטר": { s: "ליטר", p: "ליטרים" },
    "ליטרים": { s: "ליטר", p: "ליטרים" },
    "מיליליטר": { s: "מיליליטר", p: "מיליליטרים" },
    "גרם": { s: "גרם", p: "גרם" },
    "ק\"ג": { s: "ק\"ג", p: "ק\"ג" },
    "מ\"ל": { s: "מ\"ל", p: "מ\"ל" },
    "מ\"ג": { s: "מ\"ג", p: "מ\"ג" },

    // --- HEBREW INGREDIENTS ---
    "ביצה": { s: "ביצה", p: "ביצים" },
    "ביצים": { s: "ביצה", p: "ביצים" },
    "ביצה קשה": { s: "ביצה קשה", p: "ביצים קשות" },
    "ביצים קשות": { s: "ביצה קשה", p: "ביצים קשות" },
    "חלמון": { s: "חלמון", p: "חלמונים" },
    "חלמונים": { s: "חלמון", p: "חלמונים" },
    "חלבון": { s: "חלבון", p: "חלבונים" },
    "חלבונים": { s: "חלבון", p: "חלבונים" },
    "תפוח אדמה": { s: "תפוח אדמה", p: "תפוחי אדמה" },
    "תפוחי אדמה": { s: "תפוח אדמה", p: "תפוחי אדמה" },
    "תפוח אדמה בינוני": { s: "תפוח אדמה בינוני", p: "תפוחי אדמה בינוניים" },
    "תפוחי אדמה בינוניים": { s: "תפוח אדמה בינוני", p: "תפוחי אדמה בינוניים" },
    "תפוח אדמה צהוב": { s: "תפוח אדמה צהוב", p: "תפוחי אדמה צהובים" },
    "תפוחי אדמה צהובים": { s: "תפוח אדמה צהוב", p: "תפוחי אדמה צהובים" },
    "בטטה": { s: "בטטה", p: "בטטות" },
    "בטטות": { s: "בטטה", p: "בטטות" },
    "מיני בטטה": { s: "מיני בטטה", p: "מיני בטטות" },
    "בצל": { s: "בצל", p: "בצלים" },
    "בצלים": { s: "בצל", p: "בצלים" },
    "בצל קטן": { s: "בצל קטן", p: "בצלים קטנים" },
    "בצלים קטנים": { s: "בצל קטן", p: "בצלים קטנים" },
    "בצל גדול": { s: "בצל גדול", p: "בצלים גדולים" },
    "בצלים גדולים": { s: "בצל גדול", p: "בצלים גדולים" },
    "בצל סגול": { s: "בצל סגול", p: "בצלים סגולים" },
    "בצל ירוק": { s: "בצל ירוק", p: "בצלים ירוקים" },
    "בצלים ירוקים": { s: "בצל ירוק", p: "בצלים ירוקים" },
    "בצלצל שאלוט": { s: "בצלצל שאלוט", p: "בצלצלי שאלוט" },
    "בצלצלי שאלוט": { s: "בצלצל שאלוט", p: "בצלצלי שאלוט" },
    "כרישה": { s: "כרישה", p: "כרישות" },
    "שן שום": { s: "שן שום", p: "שיני שום" },
    "שיני שום": { s: "שן שום", p: "שיני שום" },
    "שיני": { s: "שן", p: "שיני" },
    "שן": { s: "שן", p: "שיני" },
    "גזר": { s: "גזר", p: "גזרים" },
    "גזרים": { s: "גזר", p: "גזרים" },
    "עגבניה": { s: "עגבניה", p: "עגבניות" },
    "עגבניות": { s: "עגבניה", p: "עגבניות" },
    "עגבניית שרי": { s: "עגבניית שרי", p: "עגבניות שרי" },
    "עגבניות שרי": { s: "עגבניית שרי", p: "עגבניות שרי" },
    "מלפפון": { s: "מלפפון", p: "מלפפונים" },
    "מלפפונים": { s: "מלפפון", p: "מלפפונים" },
    "מלפפון חמוץ": { s: "מלפפון חמוץ", p: "מלפפונים חמוצים" },
    "מלפפונים חמוצים": { s: "מלפפון חמוץ", p: "מלפפונים חמוצים" },
    "פלפל": { s: "פלפל", p: "פלפלים" },
    "פלפלים": { s: "פלפל", p: "פלפלים" },
    "פלפל חריף": { s: "פלפל חריף", p: "פלפלים חריפים" },
    "פלפלים חריפים": { s: "פלפל חריף", p: "פלפלים חריפים" },
    "גמבה": { s: "גמבה", p: "גמבות" },
    "גמבות": { s: "גמבה", p: "גמבות" },
    "גמבה אדומה": { s: "גמבה אדומה", p: "גמבות אדומות" },
    "חציל": { s: "חציל", p: "חצילים" },
    "חצילים": { s: "חציל", p: "חצילים" },
    "קישוא": { s: "קישוא", p: "קישואים" },
    "קישואים": { s: "קישוא", p: "קישואים" },
    "דלעת": { s: "דלעת", p: "דלעות" },
    "כרובית": { s: "כרובית", p: "כרוביות" },
    "סלק": { s: "סלק", p: "סלקים" },
    "סלקים": { s: "סלק", p: "סלקים" },
    "פטריה": { s: "פטריה", p: "פטריות" },
    "פטריות": { s: "פטריה", p: "פטריות" },
    "תפוח": { s: "תפוח", p: "תפוחים" },
    "תפוחים": { s: "תפוח", p: "תפוחים" },
    "אגס": { s: "אגס", p: "אגסים" },
    "אגסים": { s: "אגס", p: "אגסים" },
    "בננה": { s: "בננה", p: "בננות" },
    "בננות": { s: "בננה", p: "בננות" },
    "לימון": { s: "לימון", p: "לימונים" },
    "לימונים": { s: "לימון", p: "לימונים" },
	"גרידה מלימון שלם": { s: "גרידה מלימון שלם", p: "גרידה מלימונים שלמים" },
    "תפוז": { s: "תפוז", p: "תפוזים" },
    "תפוזים": { s: "תפוז", p: "תפוזים" },
    "שזיף": { s: "שזיף", p: "שזיפים" },
    "שזיפים": { s: "שזיף", p: "שזיפים" },
    "שזיף מיובש": { s: "שזיף מיובש", p: "שזיפים מיובשים" },
    "שזיפים יבשים": { s: "שזיף מיובש", p: "שזיפים מיובשים" },
    "צנונית": { s: "צנונית", p: "צנוניות" },
    "צנוניות": { s: "צנונית", p: "צנוניות" },
    "חסה": { s: "חסה", p: "חסות" },
    "חסות": { s: "חסה", p: "חסות" },
    "בישקוטי": { s: "בישקוטי", p: "בישקוטים" },
    "בישקוטים": { s: "בישקוטי", p: "בישקוטים" },
    "מקל קינמון": { s: "מקל קינמון", p: "מקלות קינמון" },
    "מקלות קינמון": { s: "מקל קינמון", p: "מקלות קינמון" },
    "שקד": { s: "שקד", p: "שקדים" },
    "שקדים": { s: "שקד", p: "שקדים" },
    "צנובר": { s: "צנובר", p: "צנוברים" },
    "צנוברים": { s: "צנובר", p: "צנוברים" },
    "אגוז": { s: "אגוז", p: "אגוזים" },
    "אגוזים": { s: "אגוז", p: "אגוזים" },
    "אגוז מלך": { s: "אגוז מלך", p: "אגוזי מלך" },
    "אגוזי מלך": { s: "אגוז מלך", p: "אגוזי מלך" },
    "כרע עוף": { s: "כרע עוף", p: "כרעי עוף" },
    "כרעי עוף": { s: "כרע עוף", p: "כרעי עוף" },
    "כרעיים": { s: "כרע", p: "כרעיים" }, // Generic plural often used
    "ירך עוף": { s: "ירך עוף", p: "ירכי עוף" },
    "ירכי עוף": { s: "ירך עוף", p: "ירכי עוף" },
    "כנף": { s: "כנף", p: "כנפיים" },
    "כנפיים": { s: "כנף", p: "כנפיים" },
    "דג": { s: "דג", p: "דגים" },
    "דגים": { s: "דג", p: "דגים" },
    "קציצה": { s: "קציצה", p: "קציצות" },
    "קציצות": { s: "קציצה", p: "קציצות" },
    "פיתה": { s: "פיתה", p: "פיתות" },
    "פיתות": { s: "פיתה", p: "פיתות" },
    "חלה": { s: "חלה", p: "חלות" },
    "עלה דפנה": { s: "עלה דפנה", p: "עלי דפנה" },
    "עלי דפנה": { s: "עלה דפנה", p: "עלי דפנה" },
	"לימון מגורר (קליפה)": { s: "לימון מגורר (קליפה)", p: "לימונים מגוררים (קליפה)" },

    // --- HEBREW MASS NOUNS (Invariants for Safety) ---
    "מים": { s: "מים", p: "מים" },
    "חלב": { s: "חלב", p: "חלב" },
    "קמח": { s: "קמח", p: "קמח" },
    "סוכר": { s: "סוכר", p: "סוכר" },
    "מלח": { s: "מלח", p: "מלח" },
    "פלפל": { s: "פלפל", p: "פלפל" },
    "שמן": { s: "שמן", p: "שמן" },
    "שמן זית": { s: "שמן זית", p: "שמן זית" },
    "חמאה": { s: "חמאה", p: "חמאה" },
    "דבש": { s: "דבש", p: "דבש" },
    "אורז": { s: "אורז", p: "אורז" },
    "קוסקוס": { s: "קוסקוס", p: "קוסקוס" },

    // --- COMPLEX HEBREW ITEMS (Found in recipes) ---
    "ביצה (טמפ' החדר)": { s: "ביצה (טמפ' החדר)", p: "ביצים (טמפ' החדר)" },
    "ביצים (טמפ' החדר)": { s: "ביצה (טמפ' החדר)", p: "ביצים (טמפ' החדר)" },
    "ביצה (L)": { s: "ביצה (L)", p: "ביצים (L)" },
    "ביצים (L)": { s: "ביצה (L)", p: "ביצים (L)" },
    "ביצה (L) בטמפרטורת החדר": { s: "ביצה (L) בטמפרטורת החדר", p: "ביצים (L) בטמפרטורת החדר" },
    "ביצים (L) בטמפרטורת החדר": { s: "ביצה (L) בטמפרטורת החדר", p: "ביצים (L) בטמפרטורת החדר" },
    "חלמון (L)": { s: "חלמון (L)", p: "חלמונים (L)" },
    "חלמונים (L)": { s: "חלמון (L)", p: "חלמונים (L)" },
    "תפוח אדמה (עדיף אדום לטיגון)": { s: "תפוח אדמה (עדיף אדום לטיגון)", p: "תפוחי אדמה (עדיף אדומים לטיגון)" },
    "תפוחי אדמה (עדיף אדומים לטיגון)": { s: "תפוח אדמה (עדיף אדום לטיגון)", p: "תפוחי אדמה (עדיף אדומים לטיגון)" },
    "חסה קרועה לרצועות": { s: "חסה קרועה לרצועות", p: "חסות קרועות לרצועות" },
    "חסות קרועות לרצועות": { s: "חסה קרועה לרצועות", p: "חסות קרועות לרצועות" },
    "בצל סגול חתוך לרצועות דקות": { s: "בצל סגול חתוך לרצועות דקות", p: "בצלים סגולים חתוכים לרצועות דקות" },
    "בצלים סגולים חתוכים לרצועות דקות": { s: "בצל סגול חתוך לרצועות דקות", p: "בצלים סגולים חתוכים לרצועות דקות" },
    "כרע (ללא עור)": { s: "כרע (ללא עור)", p: "כרעיים (ללא עור)" },
    "כרעיים (ללא עור)": { s: "כרע (ללא עור)", p: "כרעיים (ללא עור)" },
    "תפוח אדמה צהוב (קלוף וחתוך לקוביות גדולות)": { s: "תפוח אדמה צהוב (קלוף וחתוך לקוביות גדולות)", p: "תפוחי אדמה צהובים (קלופים וחתוכים לקוביות גדולות)" },
    "תפוחי אדמה צהובים (קלופים וחתוכים לקוביות גדולות)": { s: "תפוח אדמה צהוב (קלוף וחתוך לקוביות גדולות)", p: "תפוחי אדמה צהובים (קלופים וחתוכים לקוביות גדולות)" },
    "גמבה אדומה (חתוכה)": { s: "גמבה אדומה (חתוכה)", p: "גמבות אדומות (חתוכות)" },
    "גמבות אדומות (חתוכות)": { s: "גמבה אדומה (חתוכה)", p: "גמבות אדומות (חתוכות)" },
    "חציל מקולף ופרוס": { s: "חציל מקולף ופרוס", p: "חצילים מקולפים ופרוסים" },
    "חצילים מקולפים ופרוסים": { s: "חציל מקולף ופרוס", p: "חצילים מקולפים ופרוסים" },
    "בצל ירוק פרוס": { s: "בצל ירוק פרוס", p: "בצלים ירוקים פרוסים" },
    "בצלים ירוקים פרוסים": { s: "בצל ירוק פרוס", p: "בצלים ירוקים פרוסים" },
    "פלפל אדום חתוך לקוביות": { s: "פלפל אדום חתוך לקוביות", p: "פלפלים אדומים חתוכים לקוביות" },
    "פלפלים אדומים חתוכים לקוביות": { s: "פלפל אדום חתוך לקוביות", p: "פלפלים אדומים חתוכים לקוביות" },
    "בצל קצוץ גדול": { s: "בצל קצוץ גדול", p: "בצלים קצוצים גדולים" },
    "בצלים קצוצים גדולים": { s: "בצל קצוץ גדול", p: "בצלים קצוצים גדולים" },
    "עגבניה קלופה וחתוכה לקוביות": { s: "עגבניה קלופה וחתוכה לקוביות", p: "עגבניות קלופות וחתוכות לקוביות" },
    "עגבניות קלופות וחתוכות לקוביות": { s: "עגבניה קלופה וחתוכה לקוביות", p: "עגבניות קלופות וחתוכות לקוביות" },
    "פלפל חריף (חלפיניו) קצוץ": { s: "פלפל חריף (חלפיניו) קצוץ", p: "פלפלים חריפים (חלפיניו) קצוצים" },
    "פלפלים חריפים (חלפיניו) קצוצים": { s: "פלפל חריף (חלפיניו) קצוץ", p: "פלפלים חריפים (חלפיניו) קצוצים" },
    "בצל קטן (אופציונלי)": { s: "בצל קטן (אופציונלי)", p: "בצלים קטנים (אופציונלי)" },
    "בטטה (אופציונלי)": { s: "בטטה (אופציונלי)", p: "בטטות (אופציונלי)" },
    "בטטות (אופציונלי)": { s: "בטטה (אופציונלי)", p: "בטטות (אופציונלי)" },
    "דג פורל (עם או בלי ראש)": { s: "דג פורל (עם או בלי ראש)", p: "דגי פורל (עם או בלי ראש)" },
    "דגי פורל (עם או בלי ראש)": { s: "דג פורל (עם או בלי ראש)", p: "דגי פורל (עם או בלי ראש)" },
    "בצל בינוני קצוץ": { s: "בצל בינוני קצוץ", p: "בצלים בינוניים קצוצים" },
    "עגבניה (חתוכה לקוביות)": { s: "עגבניה (חתוכה לקוביות)", p: "עגבניות (חתוכות לקוביות)" },
    "עגבניות (חתוכות לקוביות)": { s: "עגבניה (חתוכה לקוביות)", p: "עגבניות (חתוכות לקוביות)" },
    "ביצה טרופה": { s: "ביצה טרופה", p: "ביצים טרופות" },
    "ביצים טרופות": { s: "ביצה טרופה", p: "ביצים טרופות" },
    "בצל ירוק (חתוך לפרוסות בעובי 2.5 ס\"מ)": { s: "בצל ירוק (חתוך לפרוסות בעובי 2.5 ס\"מ)", p: "בצלים ירוקים (חתוכים לפרוסות בעובי 2.5 ס\"מ)" },
    "בצלים ירוקים (חתוכים לפרוסות בעובי 2.5 ס\"מ)": { s: "בצל ירוק (חתוך לפרוסות בעובי 2.5 ס\"מ)", p: "בצלים ירוקים (חתוכים לפרוסות בעובי 2.5 ס\"מ)" },
    "בצל קצוץ דק (מטוגן ומקורר)": { s: "בצל קצוץ דק (מטוגן ומקורר)", p: "בצלים קצוצים דק (מטוגנים ומקוררים)" },
    "עגבניה מגורדת": { s: "עגבניה מגורדת", p: "עגבניות מגורדות" },
    "עגבניות מגורדות": { s: "עגבניה מגורדת", p: "עגבניות מגורדות" },
    "גמבה אדומה (חתוכה לרצועות)": { s: "גמבה אדומה (חתוכה לרצועות)", p: "גמבות אדומות (חתוכות לרצועות)" },
    "לימון (סחוט)": { s: "לימון (סחוט)", p: "לימונים (סחוטים)" },
    "ביצה (להברשה, מעורבבת עם מים ומלח)": { s: "ביצה (להברשה, מעורבבת עם מים ומלח)", p: "ביצים (להברשה, מעורבבות עם מים ומלח)" },
    "כרובית לבנה וטרייה": { s: "כרובית לבנה וטרייה", p: "כרוביות לבנות וטריות" },
    "בצל סגול (קלוף)": { s: "בצל סגול (קלוף)", p: "בצלים סגולים (קלופים)" },
    "זית קלמטה (ללא גלעין)": { s: "זית קלמטה (ללא גלעין)", p: "זיתי קלמטה (ללא גלעין)" },
    "זיתי קלמטה (ללא גלעין)": { s: "זית קלמטה (ללא גלעין)", p: "זיתי קלמטה (ללא גלעין)" },
    "לימון (סחוט למיץ)": { s: "לימון (סחוט למיץ)", p: "לימונים (סחוטים למיץ)" },
    "פלפל צ'ילי טרי": { s: "פלפל צ'ילי טרי", p: "פלפלי צ'ילי טריים" },
    "בצל (פרוס גס)": { s: "בצל (פרוס גס)", p: "בצלים (פרוסים גס)" },
    "בצלים (פרוסים גס)": { s: "בצל (פרוס גס)", p: "בצלים (פרוסים גס)" },
    "כרישה (חתוכה למקטעים של 10 ס\"מ)": { s: "כרישה (חתוכה למקטעים של 10 ס\"מ)", p: "כרישות (חתוכות למקטעים של 10 ס\"מ)" },
    "תפוח אדמה (או כמה שנכנס)": { s: "תפוח אדמה (או כמה שנכנס)", p: "תפוחי אדמה (או כמה שנכנס)" },
    "תפוחי אדמה (או כמה שנכנס)": { s: "תפוח אדמה (או כמה שנכנס)", p: "תפוחי אדמה (או כמה שנכנס)" },
    "בצלצל שאלוט (שלם)": { s: "בצלצל שאלוט (שלם)", p: "בצלצלי שאלוט (שלמים)" },
    "בצלצלי שאלוט (שלמים)": { s: "בצלצל שאלוט (שלם)", p: "בצלצלי שאלוט (שלמים)" },
    "מיני בטטה": { s: "מיני בטטה", p: "מיני בטטות" },
    "שזיף יבש (מגולען)": { s: "שזיף יבש (מגולען)", p: "שזיפים יבשים (מגולענים)" },
    "שזיפים יבשים (מגולענים)": { s: "שזיף יבש (מגולען)", p: "שזיפים יבשים (מגולענים)" },
	"בצלים בינוניים (קצוצים)": { s: "בצל בינוני (קצוץ)", p: "בצלים בינוניים (קצוצים)" },

    // --- ENGLISH UNITS (Standard) ---
    "cup": { s: "cup", p: "cups" },
    "cups": { s: "cup", p: "cups" },
    "tablespoon": { s: "tablespoon", p: "tablespoons" },
    "tablespoons": { s: "tablespoon", p: "tablespoons" },
    "tbsp": { s: "tbsp", p: "tbsp" }, // Abbr
    "teaspoon": { s: "teaspoon", p: "teaspoons" },
    "teaspoons": { s: "teaspoon", p: "teaspoons" },
    "tsp": { s: "tsp", p: "tsp" }, // Abbr
    "bag": { s: "bag", p: "bags" },
    "bags": { s: "bag", p: "bags" },
    "pack": { s: "pack", p: "packs" },
    "packs": { s: "pack", p: "packs" },
    "package": { s: "package", p: "packages" },
    "packages": { s: "package", p: "packages" },
    "container": { s: "container", p: "containers" },
    "containers": { s: "container", p: "containers" },
    "can": { s: "can", p: "cans" },
    "cans": { s: "can", p: "cans" },
    "carton": { s: "carton", p: "cartons" },
    "cartons": { s: "carton", p: "cartons" },
    "clove": { s: "clove", p: "cloves" },
    "cloves": { s: "clove", p: "cloves" },
    "head": { s: "head", p: "heads" },
    "heads": { s: "head", p: "heads" },
    "pinch": { s: "pinch", p: "pinches" },
    "pinches": { s: "pinch", p: "pinches" },
    "slice": { s: "slice", p: "slices" },
    "slices": { s: "slice", p: "slices" },
    "piece": { s: "piece", p: "pieces" },
    "pieces": { s: "piece", p: "pieces" },
    "stalk": { s: "stalk", p: "stalks" },
    "stalks": { s: "stalk", p: "stalks" },
    "stem": { s: "stem", p: "stems" },
    "stems": { s: "stem", p: "stems" },
    "bunch": { s: "bunch", p: "bunches" },
    "bunches": { s: "bunch", p: "bunches" },
    "bottle": { s: "bottle", p: "bottles" },
    "bottles": { s: "bottle", p: "bottles" },
    "liter": { s: "liter", p: "liters" },
    "liters": { s: "liter", p: "liters" },
    "handful": { s: "handful", p: "handfuls" },
    "cube": { s: "cube", p: "cubes" },
    "stick": { s: "stick", p: "sticks" },
    "sticks": { s: "stick", p: "sticks" },
    "leaf": { s: "leaf", p: "leaves" },
    "leaves": { s: "leaf", p: "leaves" },
    "jar": { s: "jar", p: "jars" },
    
    // --- ENGLISH MEASUREMENTS (Invariant/Short) ---
    "gr": { s: "gr", p: "gr" },
    "g": { s: "g", p: "g" },
    "kg": { s: "kg", p: "kg" },
    "ml": { s: "ml", p: "ml" },
    "l": { s: "l", p: "l" },
    "oz": { s: "oz", p: "oz" },
    "lb": { s: "lb", p: "lbs" },
    "lbs": { s: "lb", p: "lbs" },
    "small": { s: "small", p: "small" },
    "medium": { s: "medium", p: "medium" },
    "large": { s: "large", p: "large" },

    // --- ENGLISH INGREDIENTS ---
    "egg": { s: "egg", p: "eggs" },
    "eggs": { s: "egg", p: "eggs" },
    "yolk": { s: "yolk", p: "yolks" },
    "yolks": { s: "yolk", p: "yolks" },
    "white": { s: "white", p: "whites" },
    "whites": { s: "white", p: "whites" },
    "tomato": { s: "tomato", p: "tomatoes" },
    "tomatoes": { s: "tomato", p: "tomatoes" },
    "cherry tomato": { s: "cherry tomato", p: "cherry tomatoes" },
    "cherry tomatoes": { s: "cherry tomato", p: "cherry tomatoes" },
    "potato": { s: "potato", p: "potatoes" },
    "potatoes": { s: "potato", p: "potatoes" },
    "onion": { s: "onion", p: "onions" },
    "onions": { s: "onion", p: "onions" },
    "red onion": { s: "red onion", p: "red onions" },
    "carrot": { s: "carrot", p: "carrots" },
    "carrots": { s: "carrot", p: "carrots" },
    "pepper": { s: "pepper", p: "peppers" },
    "peppers": { s: "pepper", p: "peppers" },
    "bell pepper": { s: "bell pepper", p: "bell peppers" },
    "red bell pepper": { s: "red bell pepper", p: "red bell peppers" },
    "jalapeno": { s: "jalapeno", p: "jalapenos" },
    "cucumber": { s: "cucumber", p: "cucumbers" },
    "cucumbers": { s: "cucumber", p: "cucumbers" },
    "zucchini": { s: "zucchini", p: "zucchinis" },
    "zucchinis": { s: "zucchini", p: "zucchinis" },
    "eggplant": { s: "eggplant", p: "eggplants" },
    "eggplants": { s: "eggplant", p: "eggplants" },
    "leek": { s: "leek", p: "leeks" },
    "leeks": { s: "leek", p: "leeks" },
    "shallot": { s: "shallot", p: "shallots" },
    "shallots": { s: "shallot", p: "shallots" },
    "cauliflower": { s: "cauliflower", p: "cauliflowers" },
    "radish": { s: "radish", p: "radishes" },
    "radishes": { s: "radish", p: "radishes" },
    "pumpkin": { s: "pumpkin", p: "pumpkins" },
    "squash": { s: "squash", p: "squashes" },
    "apple": { s: "apple", p: "apples" },
    "apples": { s: "apple", p: "apples" },
    "orange": { s: "orange", p: "oranges" },
    "oranges": { s: "orange", p: "oranges" },
    "lemon": { s: "lemon", p: "lemons" },
    "lemons": { s: "lemon", p: "lemons" },
    "banana": { s: "banana", p: "bananas" },
    "bananas": { s: "banana", p: "bananas" },
    "prune": { s: "prune", p: "prunes" },
    "prunes": { s: "prune", p: "prunes" },
    "nut": { s: "nut", p: "nuts" },
    "nuts": { s: "nut", p: "nuts" },
    "almond": { s: "almond", p: "almonds" },
    "almonds": { s: "almond", p: "almonds" },
    "pine nut": { s: "pine nut", p: "pine nuts" },
    "pine nuts": { s: "pine nut", p: "pine nuts" },
    "biscuit": { s: "biscuit", p: "biscuits" },
    "biscuits": { s: "biscuit", p: "biscuits" },
    "cookie": { s: "cookie", p: "cookies" },
    "cookies": { s: "cookie", p: "cookies" },
    "meatball": { s: "meatball", p: "meatballs" },
    "meatballs": { s: "meatball", p: "meatballs" },
    "mushroom": { s: "mushroom", p: "mushrooms" },
    "mushrooms": { s: "mushroom", p: "mushrooms" },

    // --- COMPLEX ENGLISH ITEMS (Found in recipes) ---
    "peeled diced tomatoes": { s: "peeled diced tomato", p: "peeled diced tomatoes" },
    "diced jalapeños": { s: "diced jalapeño", p: "diced jalapeños" },
    "Red bell pepper (cut)": { s: "Red bell pepper (cut)", p: "Red bell peppers (cut)" },
    "Beaten egg": { s: "Beaten egg", p: "Beaten eggs" },
    "Beaten eggs": { s: "Beaten egg", p: "Beaten eggs" },
    "Sliced green onions": { s: "Sliced green onion", p: "Sliced green onions" },
    "Red bell pepper (diced)": { s: "Red bell pepper (diced)", p: "Red bell peppers (diced)" },
    "Chopped onion": { s: "Chopped onion", p: "Chopped onions" },
    "Eggplant (peeled and sliced)": { s: "Eggplant (peeled and sliced)", p: "Eggplants (peeled and sliced)" },
    "Large chopped onion": { s: "Large chopped onion", p: "Large chopped onions" },
    "Onion (sliced)": { s: "Onion (sliced)", p: "Onions (sliced)" },
    "Mushrooms, sliced (optional)": { s: "Mushroom, sliced (optional)", p: "Mushrooms, sliced (optional)" },
    "Chicken thighs": { s: "Chicken thigh", p: "Chicken thighs" },
    "Yellow potatoes (peeled and big cubed)": { s: "Yellow potato (peeled and big cubed)", p: "Yellow potatoes (peeled and big cubed)" },
    "Green onions (sliced into 1 inch lengths)": { s: "Green onion (sliced into 1 inch lengths)", p: "Green onions (sliced into 1 inch lengths)" },
    "Onion, diced small (fried and cooled)": { s: "Onion, diced small (fried and cooled)", p: "Onions, diced small (fried and cooled)" },
    "Grated tomato": { s: "Grated tomato", p: "Grated tomatoes" },
    "Grated tomatoes": { s: "Grated tomato", p: "Grated tomatoes" },
    "Red pepper (strips)": { s: "Red pepper (strips)", p: "Red peppers (strips)" },
    "Lemon (juiced)": { s: "Lemon (juiced)", p: "Lemons (juiced)" },
    "Hard boiled eggs": { s: "Hard boiled egg", p: "Hard boiled eggs" },
    "Egg (for wash, mixed with water/salt)": { s: "Egg (for wash, mixed with water/salt)", p: "Eggs (for wash, mixed with water/salt)" },
    "Fresh white cauliflower": { s: "Fresh white cauliflower", p: "Fresh white cauliflowers" },
    "Red onion (peeled)": { s: "Red onion (peeled)", p: "Red onions (peeled)" },
    "Fresh chili": { s: "Fresh chili", p: "Fresh chilis" },
    "Onions (roughly sliced)": { s: "Onion (roughly sliced)", p: "Onions (roughly sliced)" },
    "Leeks (cut into 10cm segments)": { s: "Leek (cut into 10cm segments)", p: "Leeks (cut into 10cm segments)" },
    "Potatoes (As many as fit!)": { s: "Potato (As many as fit!)", p: "Potatoes (As many as fit!)" },
    "Shallots (whole)": { s: "Shallot (whole)", p: "Shallots (whole)" },
    "Mini sweet potatoes": { s: "Mini sweet potato", p: "Mini sweet potatoes" },
    "Prunes (pitted)": { s: "Prune (pitted)", p: "Prunes (pitted)" },

    // --- ENGLISH MASS NOUNS (Invariants) ---
    "water": { s: "water", p: "water" },
    "milk": { s: "milk", p: "milk" },
    "flour": { s: "flour", p: "flour" },
    "sugar": { s: "sugar", p: "sugar" },
    "salt": { s: "salt", p: "salt" },
    "oil": { s: "oil", p: "oil" },
    "olive oil": { s: "olive oil", p: "olive oil" },
    "butter": { s: "butter", p: "butter" },
    "honey": { s: "honey", p: "honey" },
    "rice": { s: "rice", p: "rice" },
    "couscous": { s: "couscous", p: "couscous" }
};

/**
 * Returns the correct singular/plural form based on the amount.
 * @param {string} word - The word to convert (e.g., "ביצה" or "cups").
 * @param {number} amount - The numeric amount.
 * @returns {string} - The corrected word, or the original if not found.
 */
function getPlural(word, amount) {
    if (!word || typeof word !== 'string') return word;
    if (amount === null || amount === undefined || isNaN(amount)) return word;

    const normalized = word.trim();
    const entry = WORD_FORMS[normalized];

    if (!entry) return word;

    // Logic: 
    // If amount is 1 or less (but greater than 0), we typically use singular in recipes 
    // (e.g., "1/2 cup", "1 egg"). 
    // If amount > 1, we use plural ("2 eggs", "1.5 cups").
    // Zero is usually plural ("0 eggs"), handled by the else.
    if (amount > 0 && amount <= 1) {
        return entry.s;
    } else {
        return entry.p;
    }
}